from django.urls import path

from accounts.views import (
    EmailLoginView,
    about_us,
    citizen_register,
    contact_us,
    dashboard_admin,
    dashboard_citizen,
    dashboard_hr,
    dashboard_institution,
    government_business_edit,
    government_business_delete,
    government_businesses,
    government_citizens,
    hr_access_request,
    government_institution_edit,
    government_institution_delete,
    government_institutions,
    home,
    institution_access_request,
    logout_view,
    forgot_password_request,
    forgot_password_verify,
    role_based_redirect,
    vacancies_and_opportunities,
)

urlpatterns = [
    path("", home, name="home"),
    path("about-us/", about_us, name="about_us"),
    path("contact-us/", contact_us, name="contact_us"),
    path("vacancies-opportunities/", vacancies_and_opportunities, name="vacancies_opportunities"),
    path("login/", EmailLoginView.as_view(), name="login"),
    path("forgot-password/", forgot_password_request, name="forgot_password_request"),
    path("forgot-password/verify/", forgot_password_verify, name="forgot_password_verify"),
    path("logout/", logout_view, name="logout"),
    path("request/institution-access/", institution_access_request, name="institution_access_request"),
    path("request/hr-access/", hr_access_request, name="hr_access_request"),
    path("citizen-register/", citizen_register, name="citizen_register"),
    path("redirect/", role_based_redirect, name="role_redirect"),
    path("dashboard/admin/", dashboard_admin, name="dashboard_admin"),
    path("dashboard/admin/citizens/", government_citizens, name="government_citizens"),
    path("dashboard/admin/institutions/", government_institutions, name="government_institutions"),
    path(
        "dashboard/admin/institutions/<int:pk>/edit/",
        government_institution_edit,
        name="government_institution_edit",
    ),
    path(
        "dashboard/admin/institutions/<int:pk>/delete/",
        government_institution_delete,
        name="government_institution_delete",
    ),
    path("dashboard/admin/businesses/", government_businesses, name="government_businesses"),
    path(
        "dashboard/admin/businesses/<int:pk>/edit/",
        government_business_edit,
        name="government_business_edit",
    ),
    path(
        "dashboard/admin/businesses/<int:pk>/delete/",
        government_business_delete,
        name="government_business_delete",
    ),
    path("dashboard/institution/", dashboard_institution, name="dashboard_institution"),
    path("dashboard/hr/", dashboard_hr, name="dashboard_hr"),
    path("dashboard/citizen/", dashboard_citizen, name="dashboard_citizen"),
]
