# Generated by Django 6.0.2 on 2026-04-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_hrprofile'),
        ('accounts', '0002_passwordresetrequest'),
    ]

    operations = [
    ]
