# Generated by Django 6.0.2 on 2026-04-08 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_certificaterecord_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterecord',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
